stages:
  - update

variables:
  GITLAB_FORCE_RUNNING_PIPELINE: "no"

workflow:
  rules:
    # Trigger the pipeline only whenever we push new code to the main branch (via merge request).
    - if: $CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH == 'main'
    # It is possible to manually trigger this pipeline by setting this variable to 'yes'.
    - if: $GITLAB_FORCE_RUNNING_PIPELINE == 'yes'

before_script:
  - git lfs install
  - git fetch --all
  - git checkout -f main

after_script:
  # We do not need to store the .git folder on the runner disk, since we do not trigger this pipeline very often.
  - rm -rf .git

update-gitlab-runner1:
  stage: update
  tags:
    - gitlab-runner1
  script:
    - echo "Pipeline successfully triggered on gitlab-runner1"

update-gitlab-runner2:
  stage: update
  tags:
    - gitlab-runner2
  script:
    - echo "Pipeline successfully triggered on gitlab-runner2"